# Generated by Django 3.1.5 on 2021-06-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Стоимость услуги')),
            ],
        ),
    ]
