# Generated by Django 3.1.5 on 2021-06-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Стоимость услуги'),
        ),
    ]
