# Generated by Django 3.1.5 on 2021-06-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20210627_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(default=0, max_length=255, null=True, verbose_name='Стоимость услуги'),
        ),
    ]
