# Generated by Django 3.1.5 on 2021-06-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20210627_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.CharField(default=' ', max_length=255, verbose_name='Стоимость услуги'),
            preserve_default=False,
        ),
    ]
