# Generated by Django 3.1.5 on 2021-06-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20210627_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.TextField(max_length=255, verbose_name='Наименование услуги'),
        ),
    ]
