# Generated by Django 3.1.5 on 2021-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_auto_20210627_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.TextField(max_length=255, verbose_name='Стоимость услуги'),
        ),
    ]
