# Generated by Django 3.1.5 on 2021-06-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20210627_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.TextField(default='-', max_length=255, verbose_name='Стоимость услуги'),
        ),
    ]
