# Generated by Django 3.1.5 on 2021-06-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20210627_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Имя контакта')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL адрес')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='DefaultContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='EMAIL адрес')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Основные Контакты',
                'verbose_name_plural': 'Основные Контакты',
            },
        ),
    ]
